[package]
name = "testing_table"
version = "0.0.0"
edition = "2018"
publish = false

[features]
ansi = ["ansitok"]

[dependencies]
ansitok = { version = "0.2", optional = true }
unicode-width = "0.1"
