[package]
name = "terminal_size"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
terminal_size = "0.2.1"
tabled = { path = "../..", features = ["std"], default-features = false }
